spring.application.name=TodoAPI


server.address=0.0.0.0
server.port=8080

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:Todo
spring.h2.console.enabled=true
spring.datasource.username=britt
spring.datasource.password=0611

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
